// 临床指南 mock 数据
// 从 clinical-guidelines-client.tsx 抽取。

export const clinicalGuidelines = [
  {
    id: "cg-001",
    title: "2型糖尿病诊疗指南",
    organization: "中华医学会糖尿病学分会",
    publishDate: "2023-03-15",
    updateDate: "2023-03-15",
    version: "2023版",
    category: "内分泌科",
    subcategory: "糖尿病",
    recommendationCount: 42,
    evidenceLevels: ["A", "B", "C", "D"],
    keyPoints: [
      "强调个体化血糖控制目标",
      "推荐二甲双胍作为一线用药",
      "更新了心血管获益药物的应用建议",
      "增加了糖尿病技术应用的内容",
    ],
    summary:
      "本指南基于最新循证医学证据，提供了2型糖尿病的筛查、诊断、治疗和随访管理的全面建议。强调了个体化治疗策略，并更新了药物治疗和并发症管理的内容。",
    url: "https://example.com/guidelines/diabetes-2023",
    isFavorite: true,
    downloadCount: 1245,
  },
  {
    id: "cg-002",
    title: "高血压诊疗指南",
    organization: "中国高血压联盟",
    publishDate: "2022-11-08",
    updateDate: "2022-11-08",
    version: "2022版",
    category: "心血管科",
    subcategory: "高血压",
    recommendationCount: 38,
    evidenceLevels: ["A", "B", "C"],
    keyPoints: [
      "更新了高血压的诊断标准",
      "强调了家庭血压监测的重要性",
      "提供了不同人群的降压目标",
      "更新了药物治疗的推荐方案",
    ],
    summary:
      "本指南提供了高血压的预防、筛查、诊断和治疗的最新建议。基于最新研究证据，更新了高血压的分级标准和治疗目标，并强调了生活方式干预的重要性。",
    url: "https://example.com/guidelines/hypertension-2022",
    isFavorite: false,
    downloadCount: 987,
  },
  {
    id: "cg-003",
    title: "冠心病二级预防指南",
    organization: "中华心血管病学会",
    publishDate: "2022-09-20",
    updateDate: "2023-01-15",
    version: "2022版(2023更新)",
    category: "心血管科",
    subcategory: "冠心病",
    recommendationCount: 35,
    evidenceLevels: ["A", "B", "C", "D"],
    keyPoints: [
      "强调多重危险因素的综合管理",
      "更新了他汀类药物的应用建议",
      "明确了抗血小板治疗的持续时间",
      "提供了心脏康复的具体方案",
    ],
    summary:
      "本指南聚焦于冠心病患者的二级预防策略，包括危险因素控制、药物治疗和生活方式干预。基于最新临床试验结果，更新了抗血小板和调脂治疗的建议。",
    url: "https://example.com/guidelines/coronary-heart-disease-2022",
    isFavorite: true,
    downloadCount: 856,
  },
  {
    id: "cg-004",
    title: "社区获得性肺炎诊疗指南",
    organization: "中华医学会呼吸病学分会",
    publishDate: "2022-06-12",
    updateDate: "2022-06-12",
    version: "2022版",
    category: "呼吸科",
    subcategory: "感染性疾病",
    recommendationCount: 30,
    evidenceLevels: ["A", "B", "C"],
    keyPoints: [
      "更新了病原学诊断方法",
      "提供了抗生素选择的流程图",
      "明确了重症肺炎的识别标准",
      "增加了特殊人群的治疗建议",
    ],
    summary:
      "本指南提供了社区获得性肺炎的诊断、评估和治疗的最新建议。基于最新微生物学和临床研究，更新了病原体检测和抗生素治疗的内容，并强调了严重程度评估的重要性。",
    url: "https://example.com/guidelines/pneumonia-2022",
    isFavorite: false,
    downloadCount: 723,
  },
  {
    id: "cg-005",
    title: "慢性阻塞性肺疾病诊疗指南",
    organization: "中华医学会呼吸病学分会",
    publishDate: "2021-12-05",
    updateDate: "2023-02-18",
    version: "2021版(2023更新)",
    category: "呼吸科",
    subcategory: "慢性气道疾病",
    recommendationCount: 36,
    evidenceLevels: ["A", "B", "C", "D"],
    keyPoints: [
      "更新了COPD的分类标准",
      "提供了药物治疗的阶梯方案",
      "明确了急性加重的处理策略",
      "增加了肺康复的具体建议",
    ],
    summary:
      "本指南提供了慢性阻塞性肺疾病的诊断、评估、治疗和管理的全面建议。基于最新研究证据，更新了疾病分类和药物治疗的内容，并强调了非药物治疗的重要性。",
    url: "https://example.com/guidelines/copd-2021",
    isFavorite: false,
    downloadCount: 645,
  },
  {
    id: "cg-006",
    title: "急性缺血性脑卒中诊疗指南",
    organization: "中华神经科学会",
    publishDate: "2022-08-30",
    updateDate: "2022-08-30",
    version: "2022版",
    category: "神经内科",
    subcategory: "脑血管病",
    recommendationCount: 40,
    evidenceLevels: ["A", "B", "C"],
    keyPoints: [
      "更新了溶栓治疗的时间窗",
      "明确了机械取栓的适应症",
      "提供了卒中单元的建设标准",
      "增加了早期康复的具体方案",
    ],
    summary:
      "本指南提供了急性缺血性脑卒中的早期识别、评估和治疗的最新建议。基于最新临床试验结果，更新了再灌注治疗的适应症和禁忌症，并强调了卒中中心建设的重要性。",
    url: "https://example.com/guidelines/stroke-2022",
    isFavorite: true,
    downloadCount: 912,
  },
  {
    id: "cg-007",
    title: "抑郁症诊疗指南",
    organization: "中华精神医学会",
    publishDate: "2022-04-16",
    updateDate: "2022-04-16",
    version: "2022��",
    category: "精神科",
    subcategory: "情感障碍",
    recommendationCount: 32,
    evidenceLevels: ["A", "B", "C", "D"],
    keyPoints: [
      "更新了抑郁症的诊断标准",
      "提供了抗抑郁药物选择的流程图",
      "明确了心理治疗的适应症",
      "增加了难治性抑郁症的处理策略",
    ],
    summary:
      "本指南提供了抑郁症的筛查、诊断、治疗和随访管理的全面建议。基于最新研究证据，更新了药物治疗和心理治疗的内容，并强调了个体化治疗的重要性。",
    url: "https://example.com/guidelines/depression-2022",
    isFavorite: false,
    downloadCount: 578,
  },
  {
    id: "cg-008",
    title: "骨质疏松症诊疗指南",
    organization: "中华骨质疏松症学会",
    publishDate: "2022-10-10",
    updateDate: "2022-10-10",
    version: "2022版",
    category: "内分泌科",
    subcategory: "代谢性骨病",
    recommendationCount: 28,
    evidenceLevels: ["A", "B", "C"],
    keyPoints: [
      "更新了骨质疏松症的诊断标准",
      "提供了药物治疗的选择策略",
      "明确了骨折风险评估的方法",
      "增加了特殊人群的管理建议",
    ],
    summary:
      "本指南提供了骨质疏松症的预防、筛查、诊断和治疗的最新建议。基于最新研究证据，更新了诊断标准和药物治疗的内容，并强调了骨折风险评估的重要性。",
    url: "https://example.com/guidelines/osteoporosis-2022",
    isFavorite: false,
    downloadCount: 432,
  },
]

// 模拟推荐数据
export const recommendationData = [
  {
    id: "rec-001",
    guidelineId: "cg-001",
    content: "对于新诊断的2型糖尿病患者，推荐二甲双胍作为一线降糖药物，除非有禁忌症。",
    evidenceLevel: "A",
    strength: "强推荐",
    category: "药物治疗",
    references: [
      {
        id: "ref-001",
        title:
          "Effect of intensive blood-glucose control with metformin on complications in overweight patients with type 2 diabetes (UKPDS 34)",
        authors: "UK Prospective Diabetes Study (UKPDS) Group",
        journal: "Lancet",
        year: 1998,
        volume: "352",
        pages: "854-865",
        doi: "10.1016/S0140-6736(98)07037-8",
      },
      {
        id: "ref-002",
        title: "10-year follow-up of intensive glucose control in type 2 diabetes",
        authors: "Holman RR, Paul SK, Bethel MA, Matthews DR, Neil HA",
        journal: "N Engl J Med",
        year: 2008,
        volume: "359",
        pages: "1577-1589",
        doi: "10.1056/NEJMoa0806470",
      },
    ],
  },
  {
    id: "rec-002",
    guidelineId: "cg-001",
    content:
      "对于已确诊的2型糖尿病患者，建议将糖化血红蛋白(HbA1c)控制在7.0%以下，但应根据患者年龄、并发症和低血糖风险等因素个体化制定目标。",
    evidenceLevel: "B",
    strength: "强推荐",
    category: "治疗目标",
    references: [
      {
        id: "ref-003",
        title: "Glycemic Targets: Standards of Medical Care in Diabetes-2021",
        authors: "American Diabetes Association",
        journal: "Diabetes Care",
        year: 2021,
        volume: "44",
        pages: "S73-S84",
        doi: "10.2337/dc21-S006",
      },
    ],
  },
  {
    id: "rec-003",
    guidelineId: "cg-001",
    content: "对于2型糖尿病合并动脉粥样硬化性心血管疾病的患者，推荐使用具有心血管获益的GLP-1受体激动剂或SGLT-2抑制剂。",
    evidenceLevel: "A",
    strength: "强推荐",
    category: "药物治疗",
    references: [
      {
        id: "ref-004",
        title:
          "2019 ESC Guidelines on diabetes, pre-diabetes, and cardiovascular diseases developed in collaboration with the EASD",
        authors: "Cosentino F, Grant PJ, Aboyans V, et al.",
        journal: "Eur Heart J",
        year: 2020,
        volume: "41",
        pages: "255-323",
        doi: "10.1093/eurheartj/ehz486",
      },
    ],
  },
  {
    id: "rec-004",
    guidelineId: "cg-001",
    content: "对于2型糖尿病患者，建议每3-6个月检测一次糖化血红蛋白，根据治疗目标和药物调整需要可适当增加检测频率。",
    evidenceLevel: "C",
    strength: "一般推荐",
    category: "监测随访",
    references: [
      {
        id: "ref-005",
        title: "Glycemic Targets: Standards of Medical Care in Diabetes-2021",
        authors: "American Diabetes Association",
        journal: "Diabetes Care",
        year: 2021,
        volume: "44",
        pages: "S73-S84",
        doi: "10.2337/dc21-S006",
      },
    ],
  },
  {
    id: "rec-005",
    guidelineId: "cg-001",
    content:
      "对于2型糖尿病患者，推荐进行规律的有氧运动和抗阻运动，每周至少150分钟中等强度有氧运动，每周2-3次抗阻运动。",
    evidenceLevel: "B",
    strength: "强推荐",
    category: "生活方式干预",
    references: [
      {
        id: "ref-006",
        title: "Physical Activity/Exercise and Diabetes: A Position Statement of the American Diabetes Association",
        authors: "Colberg SR, Sigal RJ, Yardley JE, et al.",
        journal: "Diabetes Care",
        year: 2016,
        volume: "39",
        pages: "2065-2079",
        doi: "10.2337/dc16-1728",
      },
    ],
  },
]

// 模拟证据级别说明
export const evidenceLevelExplanations = [
  {
    level: "A",
    description: "来自多个随机对照试验或荟萃分析的高质量证据",
    reliability: "高",
  },
  {
    level: "B",
    description: "来自单个随机对照试验或大型非随机研究的中等质量证据",
    reliability: "中",
  },
  {
    level: "C",
    description: "来自专家共识、病例系列或小型研究的有限证据",
    reliability: "低",
  },
  {
    level: "D",
    description: "专家意见或临床经验",
    reliability: "很低",
  },
]

// 模拟推荐强度说明
export const recommendationStrengthExplanations = [
  {
    strength: "强推荐",
    description: "对大多数患者在大多数情况下应该采取的措施，收益明显大于风险",
    implication: "应该遵循，除非有令人信服的理由采取其他措施",
  },
  {
    strength: "一般推荐",
    description: "不同患者的最佳措施可能有所不同，收益和风险相近或不确定",
    implication: "需要根据个体情况和患者偏好做出决定",
  },
  {
    strength: "弱推荐",
    description: "其他措施可能同样合理，收益仅略大于风险或存在较大不确定性",
    implication: "需要充分考虑患者具体情况、价值观和偏好",
  },
  {
    strength: "不推荐",
    description: "对大多数患者在大多数情况下不应该采取的措施，风险大于收益",
    implication: "应该避免，除非有特殊情况",
  },
]
