import {
  Activity,
  BarChart3,
  Brain,
  FileText,
  Home,
  Lock,
  Settings,
  Smartphone,
  Stethoscope,
  UserCog,
  Users,
  Video,
  Workflow,
  BookOpen,
  Microscope,
  Pill,
  HeartPulse,
  Dna,
  Clipboard,
  ClipboardList,
  CalendarClock,
  BadgeAlert,
  ShieldCheck,
  Network,
  LineChart,
  PieChart,
  BarChart,
  TrendingUp,
  MessageSquare,
  ArrowUpDown,
  Award,
  CheckCircle,
  FileCheck,
  UserCheck,
  BadgeIcon as Certificate,
  Key,
  HardDrive,
  Clock,
  AlertCircle,
  Bell,
  BarChart2,
  User,
  Cog,
} from 'lucide-react';

export const navItems = [
  {
    title: '系统主页',
    href: '/',
    icon: Home,
  },
  {
    title: '智能诊断',
    icon: Brain,
    children: [
      { title: '诊断中心', href: '/ai-diagnosis', icon: Stethoscope },
      { title: '模型管理', href: '/ai-model', icon: Brain },
      { title: '诊断记录', href: '/ai-diagnosis/records', icon: FileText },
      { title: '模型训练', href: '/ai-model/training', icon: Activity },
      { title: '性能分析', href: '/ai-model/performance', icon: BarChart },
      {
        title: '模型部署',
        href: '/ai-model/deployment',
        icon: ArrowUpDown,
        description: '管理AI模型的部署环境和版本',
      },
    ],
  },
  {
    title: '患者管理',
    icon: Users,
    children: [
      { title: '患者列表', href: '/patients', icon: Users },
      { title: '病历管理', href: '/patients/records', icon: FileText },
      { title: '随访计划', href: '/patients/followup', icon: CalendarClock },
      { title: '患者分组', href: '/patients/groups', icon: Workflow },
    ],
  },
  {
    title: '临床决策',
    icon: Stethoscope,
    children: [
      { title: '决策支持', href: '/clinical-decision', icon: Stethoscope },
      { title: '治疗方案', href: '/clinical-decision/treatments', icon: Clipboard },
      { title: '临床指南', href: '/clinical-decision/guidelines', icon: BookOpen },
      { title: '药物参考', href: '/clinical-decision/medications', icon: Pill },
    ],
  },
  {
    title: '药物管理',
    icon: Pill,
    children: [
      { title: '药品目录', href: '/medications', icon: Pill },
      { title: '处方管理', href: '/medications/prescriptions', icon: ClipboardList },
      { title: '药物互作', href: '/medications/interactions', icon: Workflow },
      { title: '库存管理', href: '/medications/inventory', icon: Clipboard },
    ],
  },
  {
    title: '健康数据',
    icon: HeartPulse,
    children: [
      { title: '生命体征', href: '/health-data', icon: HeartPulse },
      { title: '检测结果', href: '/health-data/tests', icon: Activity },
      { title: '趋势分析', href: '/health-data/trends', icon: TrendingUp },
      { title: '数据导入', href: '/health-data/import', icon: Workflow },
    ],
  },
  {
    title: '医学研究',
    icon: Microscope,
    children: [
      { title: '研究项目', href: '/research', icon: Microscope },
      { title: '数据分析', href: '/research/analysis', icon: LineChart },
      { title: '样本管理', href: '/research/samples', icon: Dna },
      { title: '试验设计', href: '/research/trials', icon: Clipboard },
    ],
  },
  {
    title: '资质验证',
    icon: Certificate,
    children: [
      { title: '资质概览', href: '/certifications', icon: Award },
      { title: '资质上传', href: '/certifications/upload', icon: FileCheck },
      { title: '验证状态', href: '/certifications/status', icon: CheckCircle },
      { title: '资质管理', href: '/certifications/management', icon: UserCheck },
      { title: '验证机构', href: '/certifications/providers', icon: ShieldCheck },
      { title: '验证统计', href: '/certifications/statistics', icon: BarChart2 },
      { title: 'API配置', href: '/admin/api-config', icon: Key },
    ],
  },
  {
    title: '数据安全',
    icon: Lock,
    children: [
      { title: '安全概览', href: '/security', icon: ShieldCheck },
      { title: '访问控制', href: '/security/access', icon: UserCog },
      { title: '审计日志', href: '/security/audit', icon: ClipboardList },
      { title: '合规管理', href: '/security/compliance', icon: BadgeAlert },
      { title: '账户安全', href: '/security/account', icon: User },
    ],
  },
  {
    title: '移动应用',
    icon: Smartphone,
    children: [
      { title: '应用概览', href: '/mobile-app', icon: Smartphone },
      { title: '功能管理', href: '/mobile-app/features', icon: Settings },
      { title: '用户反馈', href: '/mobile-app/feedback', icon: MessageSquare },
      { title: '版本发布', href: '/mobile-app/releases', icon: Workflow },
    ],
  },
  {
    title: '电子病历',
    icon: FileText,
    children: [
      { title: '集成概览', href: '/ehr-integration', icon: Network },
      { title: '数据映射', href: '/ehr-integration/mapping', icon: Workflow },
      { title: '同步状态', href: '/ehr-integration/sync', icon: Activity },
      { title: '系统连接', href: '/ehr-integration/connections', icon: Settings },
      { title: '集成设置', href: '/ehr-integration/settings', icon: Cog },
    ],
  },
  {
    title: '远程会诊',
    icon: Video,
    children: [
      { title: '会诊中心', href: '/teleconsultation', icon: Video },
      { title: '排程管理', href: '/teleconsultation/schedule', icon: CalendarClock },
      { title: '专家网络', href: '/teleconsultation/experts', icon: Users },
      { title: '会诊记录', href: '/teleconsultation/records', icon: FileText },
    ],
  },
  {
    title: '统计分析',
    icon: BarChart3,
    children: [
      { title: '数据概览', href: '/analytics', icon: BarChart3 },
      { title: '趋势报告', href: '/analytics/trends', icon: LineChart },
      { title: '分布分析', href: '/analytics/distribution', icon: PieChart },
      { title: '预测模型', href: '/analytics/prediction', icon: TrendingUp },
    ],
  },
  {
    title: '系统管理',
    icon: Settings,
    children: [
      { title: '系统设置', href: '/admin/settings', icon: Settings },
      { title: '角色权限', href: '/admin/roles', icon: UserCog },
      { title: '系统日志', href: '/admin/logs', icon: FileText },
      { title: '数据备份', href: '/admin/backup', icon: HardDrive },
      { title: '计划任务', href: '/admin/tasks', icon: Clock },
      { title: '通知管理', href: '/admin/notifications', icon: Bell },
      { title: '部署检查', href: '/admin/deployment-check', icon: AlertCircle },
    ],
  },
];
